// Generated by CoffeeScript 1.9.3
(function() {
  var clockCycle, getMonthName, w;

  w = window;

  w.load_clock = function(id) {
    var bg, center, note;
    note = w.getNote(id);
    bg = w.getBackgroundDiv(note);
    bg.css('background-image', 'url("images/clock-bg.png")');
    bg.css('background-size', 'auto 85%');
    center = w.getCenterDiv(bg);
    center.html('<p class="clock-time"</p><p class="clock-date"></p>');
    return clockCycle();
  };

  clockCycle = function() {
    var d, date, h, m, now, time;
    now = new Date();
    h = now.getHours();
    m = now.getMinutes();
    if (h < 10) {
      h = '0' + h;
    }
    if (m < 10) {
      m = '0' + m;
    }
    time = h + ':' + m;
    d = now.getDate();
    m = now.getMonth();
    date = d + w.getOrdinal(d) + " " + getMonthName(m);
    $('.clock-time').html(time);
    $('.clock-date').html(date);
    return setTimeout(clockCycle, 500);
  };

  getMonthName = function(n) {
    var months;
    months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    return months[n];
  };

}).call(this);

//# sourceMappingURL=clock.js.map
