// Generated by CoffeeScript 1.9.3
(function() {
  var w;

  w = window;

  w.load_dial = function(id, data) {
    var center, knobGuid, note, values;
    values = w.readCleanLines(data);
    note = w.getNote(id);
    note.html('');
    center = w.getCenterDiv(note, false);
    w.setNoteTitle(center, values[0]);
    knobGuid = w.getGuid();
    center.html(center.html() + '<input type="text" id="knob-' + knobGuid + '">');
    return $('#knob-' + knobGuid).val(values[3]).knob({
      width: 110,
      angleArc: 250,
      angleOffset: -125,
      fgColor: '#ffffff',
      bgColor: 'rgba(255, 255, 255, 0.3)',
      readOnly: true,
      displayPrevious: true,
      min: values[1],
      max: values[2]
    });
  };

}).call(this);

//# sourceMappingURL=dial.js.map
