// Generated by CoffeeScript 1.9.3
(function() {
  var feedbackCycle, feedbackRunning, loadFeedbackText, w;

  w = window;

  feedbackRunning = false;

  w.load_feedback = function(id) {
    var bg, center, note;
    loadFeedbackText();
    if (feedbackRunning) {
      return;
    }
    feedbackRunning = true;
    note = w.getNote(id);
    bg = w.getBackgroundDiv(note);
    bg.css('background-image', 'url("images/feedback-bg.png")');
    bg.css('background-size', 'auto 85%');
    center = w.getCenterDiv(bg);
    center.html('<p class="feedback-agent"></p><p class="feedback-content"></p><p class="feedback-name"></p>');
    w._DATA['current-feedback'] = 0;
    return feedbackCycle();
  };

  feedbackCycle = function() {
    ++w._DATA['current-feedback'];
    if (w._DATA['current-feedback'] >= w._DATA['feedback-text'].length) {
      w._DATA['current-feedback'] = 0;
    }
    if (w._DATA['feedback-text'][w._DATA['current-feedback']][0] === '#') {
      $('.feedback-agent').hide();
    } else {
      $('.feedback-agent').show();
    }
    $('.feedback-agent').html(w._DATA['feedback-text'][w._DATA['current-feedback']][0]);
    $('.feedback-content').html("&quot;" + w._DATA['feedback-text'][w._DATA['current-feedback']][1] + "&quot;");
    $('.feedback-name').html(w._DATA['feedback-text'][w._DATA['current-feedback']][2]);
    return setTimeout(feedbackCycle, 15000);
  };

  loadFeedbackText = function() {
    var i, lines, results;
    lines = w.readCleanLines('feedback');
    w._DATA['feedback-text'] = [];
    i = 0;
    results = [];
    while (true) {
      w._DATA['feedback-text'][w._DATA['feedback-text'].length] = [lines[i], lines[i + 1], lines[i + 2]];
      i += 3;
      if (i >= lines.length) {
        break;
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

}).call(this);

//# sourceMappingURL=feedback.js.map
