// Generated by CoffeeScript 1.9.3
(function() {
  var w;

  w = window;

  w.load_identify = function(id) {
    var center, note;
    note = w.getNote(id);
    center = w.getCenterDiv(note);
    return center.html(id);
  };

}).call(this);

//# sourceMappingURL=id.js.map
