// Generated by CoffeeScript 1.9.3
(function() {
  var loadSlideShowNames, slideShowCycle, slideShowRunning, w;

  w = window;

  slideShowRunning = false;

  w.load_slide_show = function(id) {
    var bg, note;
    loadSlideShowNames();
    if (slideShowRunning) {
      return;
    }
    slideShowRunning = true;
    note = w.getNote(id);
    note.addClass('slide-show-target');
    bg = w.getBackgroundDiv(note);
    bg.css('background-image', 'url("images/note-point.png")');
    bg.css('background-position', 'bottom right');
    bg.css('background-repeat', 'no-repeat');
    w._DATA['current-slide-show'] = 0;
    return slideShowCycle();
  };

  slideShowCycle = function() {
    ++w._DATA['current-slide-show'];
    if (w._DATA['current-slide-show'] >= w._DATA['slide-show-names'].length) {
      w._DATA['current-slide-show'] = 0;
    }
    $('.slide-show-target').css('background-image', 'url("data/slide-show/' + w._DATA['slide-show-names'][w._DATA['current-slide-show']] + '")');
    return setTimeout(slideShowCycle, 15000);
  };

  loadSlideShowNames = function() {
    return w._DATA['slide-show-names'] = w.readCleanLines('slide-show');
  };

}).call(this);

//# sourceMappingURL=slide-show.js.map
