// Generated by CoffeeScript 1.9.3
(function() {
  var loadTweetText, tweetCycle, tweetsRunning, w;

  w = window;

  tweetsRunning = false;

  w.load_tweets = function(id) {
    var bg, center, note;
    loadTweetText();
    if (tweetsRunning) {
      return;
    }
    tweetsRunning = true;
    note = w.getNote(id);
    bg = w.getBackgroundDiv(note);
    bg.css('background-image', 'url("images/twitter-bg.png")');
    bg.css('background-size', 'auto 85%');
    center = w.getCenterDiv(bg);
    center.html('<p class="tweet tweet-content"></p><p class="tweet tweet-name"></p>');
    w._DATA['current-tweet'] = 0;
    return setTimeout(tweetCycle, w.tweetsDelay);
  };

  tweetCycle = function() {
    ++w._DATA['current-tweet'];
    if (w._DATA['current-tweet'] >= w._DATA['tweet-text'].length) {
      w._DATA['current-tweet'] = 0;
    }
    $('.tweet').fadeOut(400, function() {
      $('.tweet-name').html(w._DATA['tweet-text'][w._DATA['current-tweet']][0]);
      $('.tweet-content').html("&quot;" + w._DATA['tweet-text'][w._DATA['current-tweet']][1] + "&quot;");
      return $('.tweet').fadeIn(400);
    });
    return setTimeout(tweetCycle, w.tweetsSpeed);
  };

  loadTweetText = function() {
    var i, lines, results;
    lines = w.readCleanLines('tweets');
    w._DATA['tweet-text'] = [];
    i = 0;
    results = [];
    while (true) {
      w._DATA['tweet-text'][w._DATA['tweet-text'].length] = [lines[i], lines[i + 1]];
      i += 2;
      if (i >= lines.length) {
        break;
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

}).call(this);

//# sourceMappingURL=tweets.js.map
