// Generated by CoffeeScript 1.9.3
(function() {
  var reloadDataIframe, w;

  w = window;

  w._DATA = {};

  w._HOOKS = {};

  w.onmessage = function(e) {
    var i, name, ref, results, waiting;
    if (e.data.data === 'REFRESH') {
      location.reload();
      return;
    }
    w._DATA[e.data.source] = e.data.data;
    ref = w._HOOKS;
    results = [];
    for (name in ref) {
      waiting = ref[name];
      if (e.data.source === name) {
        results.push((function() {
          var j, len, results1;
          results1 = [];
          for (j = 0, len = waiting.length; j < len; j++) {
            i = waiting[j];
            results1.push(window.initNotes(i));
          }
          return results1;
        })());
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  reloadDataIframe = function() {
    $('#js-iframe').attr('src', 'data.html');
    return setTimeout(reloadDataIframe, 5000);
  };

  setTimeout(reloadDataIframe, 1000);

  w.readCleanLines = function(source) {
    var r, raw;
    raw = w._DATA[source].split("\n");
    return (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = raw.length; j < len; j++) {
        r = raw[j];
        if (r.trim().length > 0 && r.substr(0, 2) !== '--') {
          results.push(r.trim());
        }
      }
      return results;
    })();
  };

}).call(this);

//# sourceMappingURL=data.js.map
