// Generated by CoffeeScript 1.9.3
(function() {
  var guidCount, w;

  w = window;

  guidCount = 1000;

  w.getGuid = function() {
    return guidCount++;
  };

  w.getNote = function(i) {
    return $('div#note-' + i);
  };

  w.getBackgroundDiv = function(note) {
    note.html('<div class="note-extra-bg"></div>');
    return note.find('.note-extra-bg');
  };

  w.getCenterDiv = function(note, full) {
    if (full == null) {
      full = true;
    }
    note.addClass('note-center-outer' + (full ? '-full' : ''));
    note.html(note.html() + '<div class="note-center-inner"></div>');
    return note.find('.note-center-inner');
  };

  w.setNoteTitle = function(note, title) {
    return note.html(note.html() + '<p class="note-title">' + title + '</p>');
  };

  w.getOrdinal = function(n) {
    var m, ordinals;
    ordinals = [false, 'st', 'nd', 'rd'];
    m = n % 100;
    if (m > 10 && m < 14) {
      return 'th';
    } else {
      return ordinals[m % 10] || 'th';
    }
  };

}).call(this);

//# sourceMappingURL=utils.js.map
